name: telegram-support-bot
runtime: python
entrypoint: python main.py

resources:
  memory: 512Mi
  cpu: 100m

build:
  requirements:
    - python-3.11

env:
  - name: BOT_TOKEN
    value: "YOUR_BOT_TOKEN_HERE"
  - name: DATABASE_URL
    value: "sqlite+aiosqlite:///./bot.db"
  - name: OPERATOR_CHAT_ID